#!/usr/bin/env bash
#
# Generate 70 G4DCSmonitor macros (14 base fuels x 5 sources). Each macro
# loads its step-1 ROOT file ONCE, then runs ALL 12 casks x 6 hexants
# (72 runs), naming each output by (cask, global fuel). 70 (slow) loads ->
# 70 x 72 = 5040 outputs.
#
# Geometry: 3 side-facing 2x2 CASTOR-440 clusters (central + -x/+x) symmetric
# about the y-axis, inside a concrete storage hall (floor + 2 walls) for room
# return. Requires the recompiled 22 m world and the GeometryHall class.
#
# Usage:  ./generate_macros.sh [output_dir]
#
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/_orbit_map.sh"

OUT_DIR="${1:-macros/auto}"
mkdir -p "$OUT_DIR"

BASE_DIR="/home/turko46/data/SurfaceFlux_v3"   # moved off the slow /bigdata mount
MEAS_TIME=180   # seconds passed to /dcs-monitor/surf/startRun
NEUTRON_CASKS_PER_JOB="${NEUTRON_CASKS_PER_JOB:-1}"

SOURCES=(
  "gamma_662keV|gamma-662keV|28|1.4e14"
  "gamma_1173keV|gamma-1173keV|22|1.0e11"
  "gamma_1332keV|gamma-1332keV|20|1.0e11"
  "isotope_Eu154|isotope-Eu154|25|7.0e10"
  "neutron_Watt|neutron-Watt-a-0p85-b-3p4|10|4.16e6"
)

BASE_FUELS=(0 1 2 3 5 6 7 8 13 14 15 22 23 32)   # hexant 0
ROTS=(0 60 120 180 240 300)                       # hexants
CASKS=(0 1 2 3 4 5 6 7 8 9 10 11)                 # 12 casks: central(0-3), +x(4-7), -x(8-11)
# --- 192-detector phi/z scan block, generated once (identical for all macros) ---
# Circle of radius R about cask-0 centre (CX,CY); z-planes and phi steps match
# all_positions.txt exactly (phi=0,z=150 reproduces the old nominal placement).
DET_BLOCK="$(
  R=1350; CX=1580; CY=1580
  for Z in -1050 -750 -450 -150 150 450 750 1050; do
    printf '# ===== z = %s mm =====\n' "$Z"
    for I in $(seq 0 23); do
      PHI=$((15*I))
      read X Y <<<"$(awk -v p="$PHI" -v cx="$CX" -v cy="$CY" -v r="$R" \
        'BEGIN{a=p*atan2(0,-1)/180; printf "%.2f %.2f", cx+r*cos(a), cy+r*sin(a)}')"
      printf '/dcs-monitor/det/setPosition %s %s %s mm\n' "$X" "$Y" "$Z"
      printf '/dcs-monitor/det/setRotation 0 -90 %s\n'    "$PHI"
      printf '/dcs-monitor/det/clyc/add\n'
    done
  done
)"


# --- Multiple hot assemblies: key "cask:globalFuel" -> activity multiplier ---
declare -A HOT
#HOT["0:61"]=5.0

hot_multiplier() {                 # cask gfuel -> multiplier (default 1.0)
  local key="$1:$2"
  echo "${HOT[$key]:-1.0}"
}

N=0
for BASE in "${BASE_FUELS[@]}"; do
  BASE_PAD="$(printf '%02d' "$BASE")"

  for spec in "${SOURCES[@]}"; do
    IFS='|' read -r SUBDIR TAG NSHELLS RATE <<< "$spec"

    # Each assembly may now have a different primary count, encoded as
    # ...nEvts<N>.root by step 1. Discover the file and read N back out.
    SRC_GLOB="${BASE_DIR}/${SUBDIR}/using/surface_${TAG}_fuel${BASE}_nShells${NSHELLS}_nEvts*.root"
    matches=( $SRC_GLOB )

    if [ ! -e "${matches[0]}" ]; then
      echo "[warn] missing: $SRC_GLOB" >&2
      continue
    fi
    if [ "${#matches[@]}" -gt 1 ]; then
      echo "[warn] multiple matches for $SRC_GLOB; using ${matches[0]}" >&2
    fi
    SRC_FILE="${matches[0]}"

    # Parse the per-assembly primary count out of the filename.
    bn="$(basename "$SRC_FILE")"
    NEVTS="${bn##*_nEvts}"     # strip everything up to and incl. _nEvts
    NEVTS="${NEVTS%.root}"     # strip trailing .root

    #MAC="$OUT_DIR/run_baseFuel${BASE_PAD}_${SUBDIR}.mac"
    # Decide how to split this source into macro files.
    case "$SUBDIR" in
      neutron*) NPER="$NEUTRON_CASKS_PER_JOB" ;;   # slow -> split per cask
      *)        NPER=12 ;;                          # fast -> all 12 casks, 1 macro
    esac

    for START in $(seq 0 "$NPER" $(( ${#CASKS[@]} - 1 ))); do
        CASK_LIST=( "${CASKS[@]:$START:$NPER}" )

        if [ "$NPER" -ge "${#CASKS[@]}" ]; then
            # single-file case: keep the ORIGINAL filename exactly
            MAC="$OUT_DIR/run_baseFuel${BASE_PAD}_${SUBDIR}.mac"
        else
            FIRST_PAD="$(printf '%02d' "${CASKS[$START]}")"
            MAC="$OUT_DIR/run_baseFuel${BASE_PAD}_${SUBDIR}_cask${FIRST_PAD}.mac"
        fi

    # ---------- header: geometry built ONCE, all 12 casks at rotation 0 ----------
    cat > "$MAC" <<EOF
# ===================================================================
# Auto-generated by generate_macros.sh -- DO NOT EDIT BY HAND
#   base fuel : ${BASE}   source : ${SUBDIR}
#   Loads the ROOT file ONCE, runs 12 casks x 6 hexants (72 runs).
#   3 side-facing clusters + concrete hall (room return).
#   REQUIRES recompiled 22 m world + GeometryHall class.
# ===================================================================

/control/verbose 0
/run/verbose     0
/tracking/verbose 0
/event/verbose   0
/process/verbose 0
/process/em/verbose 0
/process/had/verbose 0

/run/numberOfThreads                32
/dcs-monitor/det/useBiasing         false
/dcs-monitor/det/setBiasingShells   1


## ## --- Nominal 
## /dcs-monitor/det/setPosition 2930.00 1580.00 150 mm
## /dcs-monitor/det/setRotation 0 -90 0
## /dcs-monitor/det/clyc/add

# Loop to place all detectors
${DET_BLOCK}

# =====================================================================
#  THREE CASTOR 440/84 clusters, side-facing 2x2 squares, SYMMETRIC
#  about the y-axis. Intra pitch 3160 mm (500 mm gaps); inter-cluster
#  gap 2000 mm (centroid pitch 7820 mm). All rot 0 (hexant on source).
#  Add-order == caskNum: central=0-3, +x=4-7, -x=8-11.
# =====================================================================
/dcs-monitor/det/setRotation           0     0     0
# --- CENTRAL cluster (caskNum 0-3); cask 0 = detector target ---
/dcs-monitor/det/setPosition        1580  1580     0 mm
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition        1580 -1580     0 mm
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition       -1580  1580     0 mm
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition       -1580 -1580     0 mm
/dcs-monitor/det/castor440/add
# --- +x cluster (caskNum 4-7) ---
/dcs-monitor/det/setPosition        6240  1580     0 mm
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition        6240 -1580     0 mm
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition        9400  1580     0 mm
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition        9400 -1580     0 mm
/dcs-monitor/det/castor440/add
# --- -x cluster (caskNum 8-11) ---
/dcs-monitor/det/setPosition       -6240  1580     0 mm
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition       -6240 -1580     0 mm
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition       -9400  1580     0 mm
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition       -9400 -1580     0 mm
/dcs-monitor/det/castor440/add

# --- storage hall (floor + 2 walls) for room return ---
/dcs-monitor/det/setPosition           0     0     0 mm
/dcs-monitor/det/setRotation           0     0     0
/dcs-monitor/det/hall/add
/dcs-monitor/det/hall/setLength      22000 mm
/dcs-monitor/det/hall/setWallInnerY   5410 mm
/dcs-monitor/det/hall/setFloorTopZ   -2040 mm
/dcs-monitor/det/hall/setUseCeiling   false

/run/initialize
/process/had/rdm/thresholdForVeryLongDecayTime 1e60 year

# source config (set ONCE; ROOT load happens lazily on first startRun)
/dcs-monitor/gun/sourceMode     CASTOR440_surface_from_TTree
/dcs-monitor/surf/sourcePid     0
/dcs-monitor/surf/smearPhi      0.005
/dcs-monitor/surf/smearZ        10.0 mm
/dcs-monitor/surf/smearAngle    0.02
/dcs-monitor/surf/smearEfrac    0.0
/dcs-monitor/surf/numPrimaries  ${NEVTS}
/dcs-monitor/surf/sourceFile    ${SRC_FILE}

/dcs-monitor/run/writePrimaryOnlyOnHit  true
/dcs-monitor/run/writePrimary           false
/dcs-monitor/run/writeSurfaceFlux       false
EOF

    ## ---------- 72 run blocks: 12 casks x 6 hexants ----------
    #for CASK in "${CASKS[@]}"; do
    # ---------- run blocks: only the casks in this chunk ----------
    for CASK in "${CASK_LIST[@]}"; do    # <-- was "${CASKS[@]}"

      for ROT in "${ROTS[@]}"; do
        GFUEL="$(lookup_global_fuel "$BASE" "$ROT")"
        GFUEL_PAD="$(printf '%02d' "$GFUEL")"
        ID="cask${CASK}_globalFuel${GFUEL_PAD}_${SUBDIR}"

        MULT="$(hot_multiplier "$CASK" "$GFUEL")"
        RATE_THIS="$(awk "BEGIN{printf \"%.6g\", ${RATE}*${MULT}}")"

        cat >> "$MAC" <<EOF

# --- cask=${CASK}  hexant rot=${ROT} deg -> global fuel ${GFUEL} ---
/dcs-monitor/surf/caskNum           ${CASK}
/dcs-monitor/surf/sourceRotZ        ${ROT} deg
/dcs-monitor/surf/decayRate         ${RATE_THIS}
/analysis/setFileName               data/nominal-all-positions/cask${CASK}/detector-response_globalFuel${GFUEL_PAD}_${SUBDIR}
/dcs-monitor/surf/startRun          ${MEAS_TIME} s
EOF
      done
    done

        N=$((N+1))
    done
  done
done

#echo "Generated ${N} macros in ${OUT_DIR} (each = 72 runs: 12 casks x 6 hexants)"
echo "Generated ${N} macros in ${OUT_DIR}"
echo "  (gamma/isotope: 72 runs each; neutron: split into ${NEUTRON_CASKS_PER_JOB}-cask macros)"
